### ISSUE TITLE
StageButtons

### ISSUE THREAD

**Issue by strataga** [pocesar/react-native-stager#3]
How can you hide the previous button and show the next button dependent on the stage index?

I tried:

```
{context.state.currentStage !== 1 &&
    <Button transparent large onPress={context.prev}>
        <Icon name="ios-arrow-dropleft-circle" />
    </Button>
}
{context.state.stages.length !== context.currentStage() &&
    <Button transparent rounded large onPress={context.next}>
        <Icon name="ios-arrow-dropright-circle" />
    </Button>
}
```

**Comment by pocesar** [comment]
you have a couple of options. I usually prefer to delegate the current control to an outside state, in the parent of `Stager` and check from there. you can use the functions in context like `context.has('prev')` or `context.has('next')` to determinate if you can show / hide the control buttons. the default implementation can show you how to do it (in https://github.com/pocesar/react-native-stager/blob/master/src/index.tsx#L445-L457) just change `this.state` to `context.state`
the docs are lackluster regarding the API, but I'll complement it soon. eventually I'll add public getters from the state, because `context.state` seems hacky

**Comment by strataga** [comment]
OK I’ll give that a shot. Thanks.

**Comment by strataga** [comment]
Ok that works. Thanks!

	   <StageButtons>
              {({ context }) => (
                <View style={{ flexDirection: 'row' }}>
                  {context.has('prev') &&
                    <Button transparent large onPress={context.prev}>
                      <Icon name="ios-arrow-dropleft-circle" />
                    </Button>
                  }
                  {context.has('next') &&
                    <Button transparent rounded large onPress={context.next}>
                      <Icon name="ios-arrow-dropright-circle" />
                    </Button>
                  }
                </View>
              )}
            </StageButtons>

**Comment by strataga** [comment]
How would you go about conditionally showing the next only on some stages?

There are some situations where the next button should be disabled until the user enters the correct information.

Example: next buttons should be disabled until the pin has 4 digits...

![screen shot 2017-09-12 at 12 45 07 pm](https://user-images.githubusercontent.com/10903600/30340480-40c66abe-97b8-11e7-87a9-ccdec49acf71.png)

**Comment by strataga** [comment]
Nvm. I just saw this.

```
<Button title="can continue" onPress={() => {
          this.setState({
            canContinue: true
          }, instance.refresh)
        }} />
```

**Comment by strataga** [comment]
Next question is, in the above example the step progress bar does not stretch across the view. How do that?

**Comment by pocesar** [comment]
the  
```
<View style={styles.progressPad} />
```
in https://github.com/pocesar/react-native-stager/blob/master/src/index.tsx#L436 is to force using 30% of the available screen width with an empty element. you can remove that and set the flex of the `styles.progressFlex` with a `flex: 1` to use all available space
